# Generated by Django 5.1 on 2025-11-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Webtoon', '0002_alter_usuario_avatar_webtoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracion_dias', models.IntegerField()),
                ('beneficios', models.TextField()),
                ('nivel', models.CharField(choices=[('Basico', 'Basico'), ('Premium', 'Premium'), ('VIP', 'VIP')], default='Basico', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Webtoon.usuario')),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Webtoon.webtoon')),
            ],
        ),
    ]
