# Generated by Django 5.1 on 2025-11-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Webtoon', '0003_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suscripcion', models.DateField()),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('es_favorito', models.BooleanField(default=False)),
                ('progreso_lectura', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='app_Webtoon.usuario')),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriptores', to='app_Webtoon.webtoon')),
            ],
        ),
    ]
