# Generated by Django 5.1 on 2025-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Webtoon', '0004_suscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
