# Generated by Django 5.1 on 2025-11-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Webtoon', '0005_alter_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_episodio', models.IntegerField()),
                ('titulo_episodio', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('vistas', models.IntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('es_gratuito', models.BooleanField(default=True)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='app_Webtoon.webtoon')),
            ],
        ),
    ]
