# Generated by Django 5.1 on 2025-11-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Webtoon', '0006_episodio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaEpisodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField()),
                ('ancho_pixel', models.IntegerField()),
                ('alto_pixel', models.IntegerField()),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='app_Webtoon.episodio')),
            ],
        ),
    ]
